version: '3.5'
services:
  eda:
    build: ./
    user: root
    volumes:
      - ./:/app
    working_dir: /app/notebook
    ports:
      - "8080:8080"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8080
